blank_issues_enabled: true
contact_links:
  - name: Hướng dẫn đóng góp chung
    url: https://d2l.aivivn.com/intro_vn.html#huong-dan-dong-gop
    about: Hãy xem qua trước khi bạn bắt đầu thực hiện bất kỳ đóng góp nào.