name: build html and tex

on: [push]

jobs:
  build_html_tex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --build-arg D2L_VER=$(date +%Y%m%d-%H%M%S) -t d2l .
    - name: build pdf
      run: docker run -i -v `pwd`:/d2l d2l
